# Generated by Django 5.0.4 on 2024-04-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_alter_products_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
