# Generated by Django 5.0.4 on 2024-04-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ccname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='ccnumber',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='cvv',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='order',
            name='expiration',
            field=models.CharField(default='', max_length=10),
        ),
    ]
